/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTopicsCreateImport } from './routes/_authenticated/topics/create'
import { Route as AuthenticatedTopicsTopicIdImport } from './routes/_authenticated/topics/$topicId'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedTopicsCreateRoute = AuthenticatedTopicsCreateImport.update({
  path: '/topics/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedTopicsTopicIdRoute = AuthenticatedTopicsTopicIdImport.update(
  {
    path: '/topics/$topicId',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/topics/$topicId': {
      id: '/_authenticated/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof AuthenticatedTopicsTopicIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/topics/create': {
      id: '/_authenticated/topics/create'
      path: '/topics/create'
      fullPath: '/topics/create'
      preLoaderRoute: typeof AuthenticatedTopicsCreateImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedIndexRoute,
    AuthenticatedTopicsTopicIdRoute,
    AuthenticatedTopicsCreateRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/",
        "/_authenticated/topics/$topicId",
        "/_authenticated/topics/create"
      ]
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/topics/$topicId": {
      "filePath": "_authenticated/topics/$topicId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/topics/create": {
      "filePath": "_authenticated/topics/create.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
