version: '3.3'

services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: project_planner
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_db_project_planner_password
    secrets:
      - pg_db_project_planner_password
    volumes:
      - pg_data_vol:/var/lib/postgresql/data

  projectplanner:
    image: mohandeblaze/project-planner:latest
    restart: always
    depends_on:
      - db
    links:
      - db:database
    ports:
      - 80:80
    secrets:
      - pg_db_project_planner_password
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      POSTGRES_DB: project_planner
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_db_project_planner_password

volumes:
  pg_data_vol:
