version: '3.3'

services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: project_planner
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_db_project_planner_password
    secrets:
      - pg_db_project_planner_password
    volumes:
      - pg_data_vol:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 5s
    networks:
      - internal

  app:
    image: mohandeblaze/project-planner:latest
    depends_on:
      - db
    ports:
      - "80:80"
    secrets:
      - pg_db_project_planner_password
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      POSTGRES_DB: project_planner
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_db_project_planner_password
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost/ping || exit 1
      interval: 5s
      timeout: 3s
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 5s
    networks:
      - internal

volumes:
  pg_data_vol:

secrets:
  pg_db_project_planner_password:
    external: true

networks:
  internal:
    driver: overlay
