worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;
        server_name project.axiomarc.com;

        # SSL certificate configuration for project.axiomarc.com
        ssl_certificate /etc/nginx/crt/fullchain.pem;
        ssl_certificate_key /etc/nginx/crt/privkey.pem;

        # Enable PFS with Diffie-Hellman key exchange
        # ssl_dhparam /etc/nginx/crt/dhparam.pem;
        ssl_prefer_server_ciphers on;

        # Disable TLS 1.2 and only allow TLS 1.3
        ssl_protocols TLSv1.3;
        # ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384';

        location / {
            proxy_pass http://app:80;  # Assuming your .NET Core app is running on the "app" service on port 80
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
