worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name axiomarc.com www.axiomarc.com;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name axiomarc.com www.axiomarc.com;

        ssl_certificate /etc/nginx/crt/certificate.crt;
        ssl_certificate_key /etc/nginx/crt/private.key;

        location / {
            proxy_pass http://app:80;  # Assuming your .NET Core app is running on the "app" service on port 80
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
