name: Deploy application

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/projects/project-planner/
            git pull --ff-only
            cd src
            docker info | grep -q "Swarm: active" || docker swarm init
            chmod +x ./cli && ./cli stack deploy
