name: Publish application

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Publish App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script_stop: true
          script: |
            # Specify the target directory
            target_directory="/home/projects/"

            # Remove the existing directory if it exists
            [ -d "$target_directory" ] && rm -rf "$target_directory" && echo "Folder removed successfully $target_directory" || echo "Folder does not exist $target_directory"

            # Create the target directory if it does not exist
            [ ! -d "$target_directory" ] && mkdir -p "$target_directory" && echo "Folder created successfully $target_directory" || echo "Folder already exists $target_directory"

            # Change to the cloned directory
            cd "$target_directory"

            # Clone the repository
            git clone https://github.com/mohandeblaze/project-planner.git

            # Change to the cloned directory
            cd project-planner/src

            # Run docker-compose up
            docker-compose up -d

            # Display the container status
            docker-compose ps
